### ISSUE TITLE
Progetto Fiderio

### ISSUE THREAD

**Issue by Defenestration123** [lucaderi/sgr#222]
Il progetto consiste in un programma in python che interroga con SNMP l'host sull'utilizzo di CPU, RAM e disco, applica il double exponential smoothing sui valori letti per predirli al tempo t+1 e crea un range all'esterno del quale verrà segnalato un warning su telegram.
Esiste anche una soglia superiore limite oltre il quale verrà sempre mandato un messaggio di warning (oltre 90%).
I vari valori verranno immagazzinati su InfluxDB dove sarà possibile visualizzare i dati anche sotto forma di grafici e tabelle. 
I warning di telegram verranno inviati dai tasks di InfluxDB in base ai valori ricevuti.

**Comment by Defenestration123** [comment]
[System Monitor.zip](https://github.com/lucaderi/sgr/files/8663333/System.Monitor.zip)

**Comment by lucaderi** [comment]
Non mi devi allegare un file zip ma fare una pull request che io posso validare, cosa che non e' possibile fare con uno zip. Vedi per favore quello che hanno fatto i tuoi compagni nel passato.

**Comment by Defenestration123** [comment]
#223 
Pull request creata

**Comment by lucaderi** [comment]
Implemented with https://github.com/lucaderi/sgr/pull/223
