### ISSUE TITLE
Estensione Wireshark con listener in Lua

### ISSUE THREAD

**Issue by LorenaModica** [lucaderi/sgr#228]
Questa estensione scritta in Lua consiste nell' integrare un listener in Wireshark che, dato un host X , fa una statistica degli host contattati da X , del numero di pacchetti che sono stati scambiati per ogni host e stima quante volte X è stato contattato a sua volta.
Le approssimazioni vengono calcolate sfruttando l' algoritmo HyperLogLog e i risultati vengono visualizzati in una finestra.

**Comment by lucaderi** [comment]
Implementato
