### ISSUE TITLE
Progetto Stagno - Implementazione Nuovi Flow Check (#6416 e #6417)

### ISSUE THREAD

**Issue by sre990** [lucaderi/sgr#250]
Implementing two new flow checks: one for reporting when visiting a "rare" (i.e. not popular) domain name for the selected ntop instance. Before emitting the first alert, ntopng must have a "learning period" for knowing what domains are popular or rare. The second one is similiar but the check is on the destination IP address of a flow.

**Comment by lucaderi** [comment]
Ci sono aggiornamenti circa questo progetto? quando verra' completato?

**Comment by sre990** [comment]
> Ci sono aggiornamenti circa questo progetto? quando verra' completato?

Buongiorno, ho avuto dei problemi ad integrare le aggiunte fatte in c++ con quelle in lua e non riesco a compilare ntopng. Credo che i problemi siano nel mio codice per la gui. A parte quello, ho fatto entrambi i check seguendo la documentazione ufficiale di ntopng. 

Ho due dubbi:
- ho inserito un ulteriore learning period oltre a quello che si trova in Prefs.h e credo che quella variabile sia la cosa che mi sta dando problemi. Devo invece usare quello che si trova già in Prefs.h? 
- ho creato due classi separate e indipendenti tra di loro per i check. Sarebbe meglio creare una nuova superclasse da cui ereditano le altre due? (cfr. UnexpectedSever che è il padre di altre quattro classi)

**Comment by lucaderi** [comment]
Chiuso per inattivita'. Quando inizierai a lavorarci prima contattami per email che rispetto a quando il ticket e' stato aperto molte cose sono cambiate.
