### ISSUE TITLE
Progetto Cau - Tool for http malware check from pcap file

### ISSUE THREAD

**Issue by caufab** [lucaderi/sgr#251]
Implementing a tool to check for malwares transited via http protocol.
Given a pcap file, looks for http flows and extracts all executable files. Theses files are then sent to an external analyser to check wether they can infect the host that received the analyzed http flow.

**Comment by lucaderi** [comment]
Come pensi di estrarre i files veicolati tramite HTTP? Sistema d'inglese che contiene parecchi errori.

**Comment by caufab** [comment]
> Come pensi di estrarre i files veicolati tramite HTTP?

Il tool usa tshark, lo abbiamo visto a settembre scorso, prima dell'esame.

> Sistema d'inglese che contiene parecchi errori.

Nella issue o nel README?

**Comment by lucaderi** [comment]
Closed by https://github.com/lucaderi/sgr/pull/252
