### ISSUE TITLE
Progetto Difranco Lavorini - Monitor SNMP 

### ISSUE THREAD

**Issue by GiulianoUnipi** [lucaderi/sgr#265]
Implementazione di uno strumento per il monitoraggio di utilizzo di CPU, RAM e Disco tramite SNMP. Tramite l’utilizzo di uno script in python e la libreria Easy SNMP si acquisiscono informazioni del Sistema che verranno memorizzate in un database (InfluxDB) per il monitoraggio. Attraverso Single Exponential Smoothing (implentato nello script python) viene calcolato il valore atteso. Tramite l’uso di task create con InfluxDB vengono generati allarmi nel caso di anomalie (per esempio utilizzo della CPU eccessivo o troppo distante dal valore atteso), questi allarmi verranno notificati tramite un bot di Telegram.

**Comment by GiulianoUnipi** [comment]
UPDATE:
Database cambiato da InfluxDB a Prometheus per l'acquisizione di dati e generazioni di allarmi. La gestione di allarmi è gestita da Alertmanager che invierà gli allarmi in un canale Telegram.

**Comment by lucaderi** [comment]
Implemented by https://github.com/lucaderi/sgr/pull/266
