### ISSUE TITLE
Progetto Ceroni-Ferretti - Utilizzo di IntelOwl

### ISSUE THREAD

**Issue by lucaferret** [lucaderi/sgr#268]
Il progetto consiste nello sviluppo di uno strumento per l'analisi di un file PCAP al fine di riconoscere indirizzi IP potenzialmente malevoli. Tale strumento utilizzerà il tool IntelOwl per svolgere l'analisi degli indirizzi IP. Gli IP, una volta estratti dal file, verranno filtrati utilizzando delle blacklist di indirizzi noti così da non sovraccaricare il tool e non usare inutilmente risorse.

**Comment by lucaderi** [comment]
Fixed by https://github.com/lucaderi/sgr/pull/274
