### ISSUE TITLE
Progetto Boni Braccini - Integrazione di Dionaea Honepot con Prometheus e Grafana

### ISSUE THREAD

**Issue by filiboni** [lucaderi/sgr#269]
Integrazione di Prometheus per il monitor di Dionaea e Cowrie Honeypot .Verranno realizzati collectors promethus che permetteranno di estrapolare i dati da Dionaea e Cowrie e di ottenere metriche dagli ambienti dove vengono eseguiti (docker).
Inoltre verrà implementato a codice (nei collector Prometheus)  il calcolo della Z-Score sulle time series  delle connessioni, così da poter  rappresentare possibili outlier.
Le time series ottenute verranno utilizzate per fare il training di un modello Prophet il quale forecast paragonato ai valori osservati sarà utile per un eventuale anomaly detection.
Il tutto verrà visualizzato tramite la realizzazione di una Dashboard su Grafana

**Comment by lucaderi** [comment]
Closed by https://github.com/lucaderi/sgr/pull/283
