### ISSUE TITLE
Progetto Cadau - Tocchini: Monitoraggio di rete per il detect di attacchi del tipo DoS volumetrico e port-scanning

### ISSUE THREAD

**Issue by TommyTokk** [lucaderi/sgr#270]
Creazione di uno script per il monitoraggio e l'analisi del traffico di rete con l'obiettivo di rilevare attacchi del tipo:
1) DoS volumetrico
2) Port- scanning

L'algoritmo sfrutterà uno sniffer di rete per recuperare i pacchetti, che verranno analizzati in cerca di comportamenti anomali.

**Comment by lucaderi** [comment]
Prima di iniziare
- definite come provare il software e dimostrare che funziona correttamente
- prevedete la creazione di serie temporali (RRD) per il monitoraggio del tool.

Avete scritto "Creazione di uno ***script*** per il monitoraggio". Non credo che ve la caverete con uno script.
