### ISSUE TITLE
Progetto Ferrari-Stanganini ricerca blackhole  

### ISSUE THREAD

**Issue by StangaSimo** [lucaderi/sgr#273]
Data la libreria pcap analizziamo i pacchetti prendendo in considerazione solo quelli con il protocollo tcp e si segnalano i possibili blackhole.  Tenendo aggiornato lo stato degli host si controlla se tornano a funzionare.

**Comment by lucaderi** [comment]
Closed by https://github.com/lucaderi/sgr/pull/292
