### ISSUE TITLE
Progetto Maestripieri - Zerini: Analisi serie temporali

### ISSUE THREAD

**Issue by GioZerini** [lucaderi/sgr#275]
Estensione dell'API di nDPI con la funzione "ndpi_predict_linear", che consente di predire un valore di una data serie temporale in un determinato istante, utilizzando la regressione lineare semplice.
Fase di testing effettuata cercando di prevedere l'occupazione di memoria e disco tra un giorno oppure una settimana.

**Comment by lucaderi** [comment]
Implemented by https://github.com/lucaderi/sgr/pull/278
