### ISSUE TITLE
Progetto Maggi: aggiunta a nDPI della feature per estrarre il filename da HTTP attachment file transfers

### ISSUE THREAD

**Issue by ChiaraMaggi** [lucaderi/sgr#282]
Il progetto consiste nell'estrarre il filename (se presente) dal Content-Disposition presente nel response header di una risposta HTTP regolare. L'aggiunta del nome del file identificherà meglio i trasferimenti sospetti/dannosi.

**Comment by lucaderi** [comment]
Come descritto in https://github.com/ntop/nDPI/issues/1970 occorre fare:
- utilizzare il pcap https://github.com/ntop/nDPI/blob/dev/tests/cfgs/default/pcap/exe_download.pcap per fare le prove
- aggiungere in src/include/ndpi_typedefs.h (riga 1445) dentro il campo http un nuovo campo chiamato char *filename;
- modificare src/lib/protocols/http.c (riga 288) e creare una funzione (o modificare il codice esistente) che processi nella risposta HTTP il campo "Content-Disposition" estraendo il filename se esistente. e lo salvi dentro il campo filename del punto precedente
- in src/lib/ndpi_main.c (attorno alla ala 5330) liberare la memoria del filename se popolata
- definire in src/reader_util.h (riga 290) il campo filename
- modificare example/reader_util.c (attorno alla riga 1392) salvando dentro flow->http.filename il campo popolato in precedenza
- modificare example/ndpiReader.c (riga 792, 1470 e 1761) aggiungendo la stampa di filename (o stringa vuota se assente)

Per vedere se non sono stati introdotti problemi eseguire tests/do.sh
