### ISSUE TITLE
Progetto Buzi: Aggiunta funzione a ipt_geofence per il calcolo del tempo di ban

### ISSUE THREAD

**Issue by AldoBuzi** [lucaderi/sgr#310]
Per il momento, nel progetto ho individuato i seguenti punti:

- Aggiungere la possibilità di scegliere il nome dell'output file da linea di comando.
- Poter scegliere se il formato del file deve essere serializzato o json.
- Poter scegliere di salvare un file in ogni caso, può essere utile come log.
- Aggiunta della funzione per il calcolo del tempo di ban necessario con parametri configurabili.

**Comment by lucaderi** [comment]
Implementato con https://github.com/ntop/ipt_geofence/pull/29
