### ISSUE TITLE
Progetto Cordisco: Plugin Wireshark per fingerprinting QUIC

### ISSUE THREAD

**Issue by lucacordisco** [lucaderi/sgr#311]
Si vuole realizzare un plugin per Wireshark che implementi il fingerprinting QUIC, ispirandosi a [quic-hunter/libraries](https://github.com/quic-hunter/libraries). Tuttavia, mentre QUIC Hunter si focalizza sulle librerie server QUIC, questo plugin sarà specificamente progettato per produrre un fingerprint per i client QUIC.

Il plugin analizzerà il ClientHello di ogni handshake QUIC e calcolerà un fingerprint per ciascuno, considerando l'insieme e l'ordine dei transport parameters.

La validità del fingerprint verrà testata catturando l'handshake con diversi client QUIC.

**Comment by lucaderi** [comment]
Closed by https://github.com/lucaderi/sgr/pull/330
