### ISSUE TITLE
Progetto D'Alessandro: analisi traffico WiFi in monitor mode

### ISSUE THREAD

**Issue by Giovy52845** [lucaderi/sgr#312]
Un'applicazione che ispeziona e analizza il traffico della rete Wi-Fi, impostando la scheda di rete in monitor mode, fornendo informazioni sulle reti circostanti, sulla qualità del segnale e sui dispositivi connessi.

**Comment by lucaderi** [comment]
Implementato con https://github.com/lucaderi/sgr/pull/314
