### ISSUE TITLE
Progetto Milano/Pacini: Processo di individuazione delle richieste malevole e la segnalazione degli indirizzi IP all'interno di un file di log

### ISSUE THREAD

**Issue by xAle00** [lucaderi/sgr#313]
Uno script Python che, all'interno di un file di log, individui le richieste malevole effettuate da un indirizzo IP specifico.
Le richieste sono raggruppate per un intervallo di tempo di 5 minuti e viene effettuata una verifica per determinare la presenza di attività malevole. 
Durante le scansioni successive, gli indirizzi IP malevoli identificati nella scansione precedenti vengono mantenuti in memoria.

**Comment by lucaderi** [comment]
Altri commenti
- s analizzano log HTTP in formato standard/Apache
- 5 minuti sono configurabili
- Le richieste sono analizzate su una sliding window di 2 x 5 minuti
- I problema rilevare includono: scansioni (no navigazione), SQL Injection, accesso a URL sospette (es quelle che iniziano con un .), tentativi di login da parte di client non localizzati in Italia

**Comment by lucaderi** [comment]
Implementato da https://github.com/lucaderi/sgr/pull/340
